#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../common/include.sh"

include "${BASH_SOURCE%/*}/../install/common.sh"
include "${BASH_SOURCE%/*}/../.ez-installrc"
include "${HOME}/.ez-installrc"

VERBOSE=true
DEBUG=true
LOG_DEBUG_LEVEL=7

_main() {
  resolve_package_dir
  local package="git"
  local res=

  local package_path="${package}"
  fetch_package package_path
  res=$?

  local package_new="${LOCAL_PACKAGE_DIR}/${package}"
  [[ "${package_new}" == "${package_path}" ]] || error "fetch_package() failed. exit code: ${res}"
}

_main
