#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../install/common.sh"

VERBOSE=true

# test() {
# 	while true; do
# 		i=0
# 		for pathname; do
# 			i=$((i + 1))
# 			printf '%d) %s\n' "$i" "$pathname" >&2
# 		done
#
# 		printf 'Select file to upload, or 0 to exit: ' >&2
# 		read -r reply
#
# 		number=$(printf '%s\n' "$reply" | tr -dc '[:digit:]')
#
# 		if [ "$number" = "0" ]; then
# 			echo 'Bye!' >&2
# 			exit
# 		elif [ "$number" -gt "$#" ]; then
# 			echo 'Invalid choice, try again' >&2
# 		else
# 			break
# 		fi
# 	done
# }
#
# test "test"

main() {
	local selected
	local list=("item1" "item2" "item3")
	local prompt="Sample prompt message: "

	# list_selector -p "${prompt}" selected "${list[@]}" 2>&1
	# select_package "test" selected "test-common"
	print_packages "test" "bats"
}

main
