#!/usr/bin/env bash

VERBOSE=true

source "${BASH_SOURCE%/*}/../install/common.sh"
source "${BASH_SOURCE%/*}/../install/install-utils/install-apt.sh"

# test() {
# 	while true; do
# 		i=0
# 		for pathname; do
# 			i=$((i + 1))
# 			printf '%d) %s\n' "$i" "$pathname" >&2
# 		done
#
# 		printf 'Select file to upload, or 0 to exit: ' >&2
# 		read -r reply
#
# 		number=$(printf '%s\n' "$reply" | tr -dc '[:digit:]')
#
# 		if [ "$number" = "0" ]; then
# 			echo 'Bye!' >&2
# 			exit
# 		elif [ "$number" -gt "$#" ]; then
# 			echo 'Invalid choice, try again' >&2
# 		else
# 			break
# 		fi
# 	done
# }
#
# test "test"

main() {
	local update+=("$(apt_add_repo -u true -s true "ppa:git-core/ppa")")
	printf '%s\n' "${update[@]}"
}

main
