#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../.ez-installrc"
source "${BASH_SOURCE%/*}/../common/include.sh"

include "${BASH_SOURCE%/*}/../const.sh"
include "${BASH_SOURCE%/*}/../install/common.sh"
include "${BASH_SOURCE%/*}/../generate/utils/generate.sh"

VERBOSE=true
DEBUG=true
LOG_DEBUG_LEVEL=7

_main() {
  generate_package 'test.apt'
  generate_package_pre 'test.apt'
  generate_package_post 'test.apt'
}

_main

