#!/usr/bin/env bash

source install/progress-bar.sh

# echo -ne '#####                     (33%)\r'
# sleep 0.5
# echo -ne '                               \r'
# echo -ne 'yes\n\n'
# echo -ne '##########                (40%)\r'
# sleep 0.5
# echo -ne '                               \r'
# echo -ne 'yes\n\n'
# echo -ne '#############             (50%)\r'
# sleep 0.5
# echo -ne '                               \r'
# echo -ne 'yes\n\n'
# echo -ne '####################      (75%)\r'
# sleep 0.5
# echo -ne '                               \r'
# echo -ne 'yes\n\n'
# echo -ne '######################### (100%)\r'
# echo -ne '\n'

for i in {1..100} ; do
  prog_bar $i
  sleep .1
  printf "\r%-110s" "yes"
  echo -ne "\nyes"
done
