#!/usr/bin/env bash

set -o pipefail
set -o nounset

source "${BASH_SOURCE%/*}/../.ez-installrc"
source "${BASH_SOURCE%/*}/../common/common.sh"
source "${BASH_SOURCE%/*}/common.sh"

SCRIPT_ARGS="${@}"

# Source custom rc file if exist
CUSTOM_EZ_INSTALL_RC="${HOME}/.ez-installrc"
if [[ -e "${CUSTOM_EZ_INSTALL_RC}" ]]; then
  source "${CUSTOM_EZ_INSTALL_RC}"
fi


usage() {
  local scriptpath="$(realpath -- "${0}")"

cat <<- EOF
$(basename -- "${scriptpath}")

USAGE:

./$(basename -- "${scriptpath}") [ -hvxy ] package

OPTIONS:

  -d --dependency       package installation dependencies
  -a --author           package author (optional)
  -D --directory-path   package output directory
  -v --verbose          verbose output
  -x --debug            debug
  -y --skip             skip confirmation
  -h --help             show usage
EOF
}

handle_args() {
  local arg=
  for arg; do
    local delim=""
    case "${arg}" in
      --dependency)       args="${args:-}-d ";;
      --author)           args="${args:-}-a ";;
      --directory-path)   args="${args:-}-D ";;
      --package-manager)  args="${args:-}-m ";;
      --pre)              args="${args:-}-p ";;
      --post)             args="${args:-}-P ";;
      --skip-confirm)     args="${args:-}-y ";;
      --verbose)          args="${args:-}-v ";;
      --debug)            args="${args:-}-x ";;
      --help)             args="${args:-}-h ";;
      *)
        [[ "${arg:0:1}" == "-" ]] || delim="\""
        args="${args:-}${delim}${arg}${delim} ";;
    esac
  done

  eval set -- ${args:-}

  [[ -z "${SKIP_CONFIRM+x}" ]]    && SKIP_CONFIRM=false
  [[ -z "${VERBOSE+x}" ]]         && VERBOSE=false
  [[ -z "${DEBUG+x}" ]]           && DEBUG=false
  [[ -z "${LOG_DEBUG_LEVEL+x}" ]] && LOG_DEBUG_LEVEL=3

  FILE=""
  DEPENDENCIES=""
  AUTHOR=""
  DIRECTORY_PATH="${PACKAGE_DIR:-${BASH_SOURCE%/*}/packages}"
  PACKAGE_MANAGER=""
  PRE_PROCESS=""
  POST_PROCESS=""

  OPTIND=1
  while getopts "a:d:D:m:p:P:vxyh" opt; do
    case ${opt} in
      a)
        AUTHOR="${OPTARG}"
        ;;
      d)
        DEPENDENCIES="${OPTARG}"
        ;;
      D)
        DIRECTORY_PATH="${OPTARG}"
        ;;
      m)
        PACKAGE_MANAGER="${OPTARG}"
        ;;
      p)
        PRE_PROCESS="${OPTARG}"
        ;;
      P)
        POST_PROCESS="${OPTARG}"
        ;;
      v)
        VERBOSE=true
        ;;
      x)
        DEBUG=true
        LOG_DEBUG_LEVEL=7
        ;;
      y)
        SKIP_CONFIRM=true
        ;;
      h)
        usage; exit 0
        ;;
    esac
  done
  shift "$((OPTIND-1))"

  if [[ -z "${1+x}" ]]; then
    error "No filename argument provided" 1
  fi
  FILE="${1}"

  return 0
}


_check_package() {
  local package="${1:-}"
  local prompt="${2:-Do you wish to continue? (Y/y): }"

  if [[ -z "${package}" ]]; then
    error "No package provided" 1
  fi

  if [[ -e "${package}" ]] && ! ${SKIP_CONFIRM}; then
    confirm "'${package}' already exists. ${prompt}" ||
      return 1
  fi
}


generate_template() {
  local file_path="${1:-}"

  _check_package "${file_path}" ||
    exit 1

cat > "${file_path}" <<- ___EOF___
#!/usr/bin/env bash

########################################################### PACKAGE METADATA ###
# ---
# package: ${FILE}
# dependency: ${DEPENDENCIES}
# author: ${AUTHOR}
# ---
################################################################################

source "\${EZ_INSTALL_HOME}/generate/common.sh"

# Set up if executed instead of sourcing
if [ "\${0##*/}" == "\${BASH_SOURCE[0]##*/}" ]; then
  source "\${EZ_INSTALL_HOME}/common/common.sh"
  script_vars
  handle_args "\${@}"
fi

################################################################# START CODE ###

# TODO: Finish ${FILE} installation template

_main() {
  # Package name defaults to filename
  local package="\$(basename -- "\${BASH_SOURCE}")"
  local package_manager="\${PACKAGE_MANAGER:-${PACKAGE_MANAGER}}"

  # Get system package manager
  [[ -z "\${package_manager}" ]] && get_sys_package_manager package_manager

  # Pre process
  ${PRE_PROCESS}

  # Install package
  if install "\${package_manager}" "\${package}"; then
    # Post process
    ${POST_PROCESS}
    local res=\$?
    return \${res}
  fi
}

################################################################### END CODE ###

_main
unset PACKAGE_MANAGER
# SOURCED BY \`pac-install()\`, DO NOT USE \`exit\`. USE \`return\` INSTEAD
___EOF___

  chmod +x "${file_path}" && echo -e "${file_path} created!"
}


_main() {
  handle_args "${SCRIPT_ARGS}"
  if [[ -z "${PACKAGE_MANAGER}" ]]; then
    local file_path="${DIRECTORY_PATH}/${FILE}"
  else
    local file_path="${DIRECTORY_PATH}/${FILE}.${PACKAGE_MANAGER}"
  fi

  if [[ ! -d "${DIRECTORY_PATH}" ]]; then
    mkdir -p "${DIRECTORY_PATH}"
  fi
  generate_template "${file_path}"
}


_main

unset FILE
unset DEPENDENCIES
unset AUTHOR
unset DIRECTORY_PATH
unset PRE_PROCESS
unset POST_PROCESS
