#!/usr/bin/env bash

set -o pipefail
set -o nounset

source "${BASH_SOURCE%/*}/common.sh"

SCRIPT_DIR="${BASH_SOURCE%/*}"

_main() {
  local -a packages=(
    "build-essential"
    "libssl-dev"
    "libffi-dev"
    "git"
    "-d git git-lfs"
    "-d git lazygit"
    "yarn"
    "curl"
    "wget"
    "zip"
    "unar"
    "gnupg2"
    "net-tools"
  )

  for package in "${packages[@]}"; do
    ${SCRIPT_DIR}/generate-template -y "${package}"
  done
}

_main
