#!/usr/bin/env bash

set -o pipefail
set -o nounset

source "${BASH_SOURCE%/*}/../install/common.sh"

SCRIPT_DIR="${BASH_SOURCE%/*}"

_main() {
  local -a essentials=(
    "build-essential"
    "libssl-dev"
    "libffi-dev"
    "cmake"
    "curl"
    "wget"
    "zip"
    "unzip"
    "unar"
    "git"
    "-d git git-lfs"
    "gnupg2"
    "net-tools"
  )

  local -a package_manager=(
    "-m npm browser-sync"
    "-m npm gulp-cli"
  )

  local -a languages=(
    # Python
    "python3-dev"
    "libffi-dev"
    "libssl-dev"
    "python3-pip"
    "python3-venv"
    # Java
    "default-jre"
    "default-jdk"
    "openjdk-8-jdk"
    "openjdk-8-jre"
    "openjdk-11-jdk"
    "openjdk-11-jre"
    "openjdk-13-jdk"
    "openjdk-13-jre"
    "maven"
    # R
    "r-base"
  )

  local -a packages=(
    "${essentials[@]}"
    "${package_manager[@]}"
  )

  for package in "${packages[@]}"; do
    ${SCRIPT_DIR}/generate-template -y "${package}"
  done
}

_main
