#!/usr/bin/env bash

set -o pipefail
set -o nounset

source "${BASH_SOURCE%/*}/../common/common.sh"
source "${BASH_SOURCE%/*}/common.sh"

SCRIPT_ARGS="${@}"
PACKAGE_DIR="${PACKAGE_DIR:-${BASH_SOURCE%/*}/packages}"


_check_package() {
  local package="${1:-}"
  local prompt="${2:-Do you wish to continue? (Y/y): }"

  if [[ -z "${package}" ]]; then
    usage
    error "No package provied" 1
  fi

  if [[ ! -e "${PACKAGE_DIR}/${package}" ]]; then
    error "${PACKAGE_DIR}/${package} not found" 1
  fi

  confirm "${prompt}"
  return $?
}


_main() {
  script_vars
  handle_args "${SCRIPT_ARGS}"

  _check_package "${PACKAGE}" "You are about to install '${PACKAGE}'. Do you wish to continue? (Y/y): " || \
    exit 1

  source ${PACKAGE_DIR}/${PACKAGE}
}


_main

