#!/usr/bin/env bash

set -o pipefail
set -o nounset

source "${EZ_INSTALL_HOME}/common/colors.sh"
source "${EZ_INSTALL_HOME}/common/log.sh"
source "${EZ_INSTALL_HOME}/install/utils/actions.sh"


[[ -z "$@" ]] && error "No arguments passed" 1

[[ -z "${VERBOSE+x}" ]] && VERBOSE=true
META="${1:?}"

if [[ "${2+x}" ]]; then
  FILE="${2}"
  if [[ ! -f "${FILE}" ]]; then
    error "Missing ${FILE} file" 1
  fi
else
  error "No file provided" 1
fi

main() {
  local start_parsing=true

  while IFS="" read -r line; do
    if [[ "${line}" == "# ---" ]]; then
      if ${start_parsing}; then
        start_parsing=false
        continue
      else
        return 0
      fi
    fi

    if ! ${start_parsing} && [[ "${line}" =~ "${META}" ]]; then
      printf '%s\n' "${line}" | awk -F ':' '{print $2}' | xargs
    fi
  done < "${FILE}"
}

main

unset VERBOSE
unset META
