#!/usr/bin/env bash

set -o pipefail
set -o nounset

source "${BASH_SOURCE%/*}/../../common/colors.sh"
source "${BASH_SOURCE%/*}/../../common/log.sh"

[[ -z "$@" ]] && log 'error' "No arguments passed" 1

META="${1:?}"

if [[ ${2+x} ]]; then
  FILE="${2}"
  if [[ ! -f "${FILE}" ]]; then
    log 'error' "Missing ${FILE} file" 1
  fi
else
  log 'error' "No file provided" 1
fi

main() {
  local _start_parsing=0

  while IFS="" read -r line; do
    if [[ "${line}" == "# ---" ]]; then
      if [[ $_start_parsing -eq 0 ]]; then
        _start_parsing=1
        continue
      else
        return 0
      fi
    fi

    if [[ ${_start_parsing} -eq 1 ]] && [[ "${line}" =~ "${META}" ]]; then
      printf '%s\n' "${line}" | awk -F ':' '{print $2}' | xargs
    fi
  done < "${FILE}"
}

main

unset META
